### ISSUE TITLE
Locked - not sending

### ISSUE THREAD

**Issue by sargantana** [minad/3delta#2]
Printer is connected but I cant control it with the software. I tried different USB Ports, but it still occurs.
I dont get what is the issue, as serial communication is not locked or something, Repetierhost and Printrun are working and communicating with it.
I am using Ubuntu 14.04, a Kossel PRO, the RepRap Marlin firmware and a standart USB cable to connect to the Board.

**Comment by minad** [comment]
There is a small checkbox next to the prompt which is used to lock the communication. This is used to ensure that an active print is not interrupted by clicking around in the gui.
